- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> feat: homepage

- app/controllers/islands_controller.rb
- app/models/island.rb
- app/models/user.rb
- app/views/islands/create.html.erb
- app/views/islands/index.html.erb
- app/views/islands/new.html.erb
- app/views/islands/show.html.erb
- config/routes.rb
- db/migrate/20191203100815_create_islands.rb
- db/schema.rb
- test/controllers/islands_controller_test.rb
- test/models/island_test.rb
The model and controller for the island and the corresponding views created!
Give feedback!
> island model created with island controller

- app/assets/stylesheets/components/_navbar.scss
> FIX: navbar

- app/views/pages/home.html.erb
> fix: homepage button

- app/views/layouts/application.html.erb
Removed notice and alert from application.html.erb
> FIX: remove the notice and alert from application.html.erb

- app/views/islands/index.html.erb
- db/seeds.rb
Added fields to index page and fixed seed file for price field
> FIX: Working on correction for seed file

- app/views/islands/index.html.erb
Please merge for index to work
> fixed index

- app/views/islands/index.html.erb
> FEATURE: add link to index page

- app/views/shared/_navbar.html.erb
Fixed the navbar links, made them functional.
Log in/Log out toggleable depending on if the user is signed in or not
> navbar links functional

- app/assets/stylesheets/pages/_home.scss
- app/views/islands/new.html.erb
- app/views/pages/home.html.erb
Added link functionality in homepage. Please review!
> FIX: homepage link directs user to index page

- app/assets/stylesheets/pages/_show.scss
Added to required closing curly bracket
> FIX: added curly bracket to close scss

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Both sign in and sign up pages created!
> FEAT sign up sign in css done

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/islands/show.html.erb
I changed the image and font size
> Show style

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_new.scss
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/islands/new.html.erb
Css for new island and buttons for sign in sign up changes made.
> FEAT new island form css done

- app/assets/stylesheets/pages/_show.scss
- app/views/islands/show.html.erb
Added a book button to the show page
> FEAT: book button

- app/assets/stylesheets/pages/_home.scss
> FIX home page fixed

- app/assets/stylesheets/pages/_show.scss
- app/views/islands/show.html.erb
Changed name of button class to btn-book
> FIX: changed name of button class to btn-book

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_show.scss
Moved btn-book css to the button component
> FIX: moved btn-book to button component

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> FEAT: search bar added to navbar

- app/assets/stylesheets/components/_button.scss
> FIX: add hover to book button

- app/views/islands/new.html.erb
I changed the simple_form input from a list of locations to a user input. Please review and merge
> FIX: allow user to provide a custom location for a new island

- app/models/booking.rb
- app/models/island.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20191205105121_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
Generated the Booking model and routes
> Booking model

- app/controllers/bookings_controller.rb
- app/views/bookings/create.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/islands/show.html.erb
- config/routes.rb
- test/controllers/bookings_controller_test.rb
Created the bookings controller and views
> Created bookings controller and views

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- config/routes.rb
methods for accept and decline done!
> FEAT reject and accept methods done

- app/controllers/islands_controller.rb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Adding a simple search feature
> initial search function implemented

- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
buttons for accept and reject done! no cancel button for bookings!
> FIX reject and accept methods done

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_utilities.scss
- app/views/devise/sessions/new.html.erb
> Login backup
